name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate Gradle Wrapper & Build APK
      run: |
        gradle wrapper --gradle-version 6.1.1
        chmod +x gradlew
        ./gradlew assembleRelease
      # إذا كان مشروع الأندرويد داخل مجلد فرعي، أضف سطر مسار العمل هنا، مثلاً:
      # working-directory: ./اسم_المجلد_الفرعي
